spring:
  application:
    name: borsa

  datasource:
    url: jdbc:postgresql://localhost:5432/borsa_db
    username: postgres
    password: YOUR_PASSWORD_HERE
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8080

jwt:
  secret: YOUR_JWT_SECRET_HERE
  expiration: 86400000